# Generated by Django 6.0.4 on 2026-05-21 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('auditor', 'Auditor'), ('analyst', 'Analista de soporte'), ('consultant', 'Consultor'), ('client', 'Cliente')], default='client', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='telefono')),
                ('company', models.CharField(blank=True, max_length=140, verbose_name='empresa')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'perfil de usuario',
                'verbose_name_plural': 'perfiles de usuario',
            },
        ),
    ]
