# Generated by Django 6.0.4 on 2026-05-21 22:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_number', models.CharField(max_length=40, unique=True, verbose_name='numero interno')),
                ('git_ticket', models.CharField(blank=True, max_length=80, verbose_name='ticket GIT')),
                ('label', models.CharField(max_length=120, verbose_name='etiqueta')),
                ('description', models.TextField(verbose_name='descripcion')),
                ('opened_at', models.DateField(default=django.utils.timezone.localdate, verbose_name='fecha de apertura')),
                ('resolved_at', models.DateField(blank=True, null=True, verbose_name='fecha de resolucion')),
                ('reported_by', models.CharField(max_length=140, verbose_name='informado por')),
                ('reporter_position', models.CharField(blank=True, max_length=120, verbose_name='cargo')),
                ('reporter_email', models.EmailField(max_length=254, verbose_name='correo')),
                ('reporter_phone', models.CharField(blank=True, max_length=40, verbose_name='telefono')),
                ('observations', models.TextField(blank=True, verbose_name='observaciones')),
                ('no_client_response', models.BooleanField(default=False, verbose_name='cerrado sin respuesta del cliente')),
                ('negative_feedback', models.BooleanField(default=False, verbose_name='feedback negativo de producto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('business_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='catalogos.businessline')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='catalogos.client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tickets', to=settings.AUTH_USER_MODEL)),
                ('escalated_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='catalogos.escalationgroup')),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='catalogos.priority')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='catalogos.product')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='catalogos.ticketstatus')),
            ],
            options={
                'ordering': ['-opened_at', '-created_at'],
                'permissions': [('close_ticket', 'Puede cerrar tickets'), ('export_ticket', 'Puede exportar tickets')],
            },
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tickets.ticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=160, verbose_name='accion')),
                ('next_step', models.CharField(blank=True, max_length=200, verbose_name='siguiente paso')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='tickets.ticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='tickets.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historial de ticket',
                'verbose_name_plural': 'historial de tickets',
                'ordering': ['-created_at'],
            },
        ),
    ]
